name: Mad Weight Loss
markdown: redcarpet
pygments: true
gituser: brijeshb42/bitwiser
paginate: 5
paginate_path: "page:num"
email: info@themaddiet.com
#disqus: bitwiser
ga_id: UA-47902363-1
ga_domain: bitwiser.in
desc: Mad Weight Loss, LLC. Lose Weight & Feel Great!
keywords: bitwiser, jekyll, theme, templates
twitter: brijeshb42